# BCT Coding into Fitbit Work
**1.1 Goal Setting (behavior)**
    Uses and pays attention to a goal.

**1.4 Action Planning**
    Individual creates a plan to be physically active.

 **1.5 Review Behavior Goals**
    Self-review of step/activity goals with evaluation. If goals are moved repeatedly, can code as 8.7 Graded Tasks.

**1.6 Discrepancy Between Current Behavior and Goal**
    Having the data and checking it against the goal prompts behavior

**2.2 Feedback on Behavior**
    Information about actual behavior in real-time (steps, distance, hr, etc)

**2.3 Self-monitoring of Behavior**
    Recording and interacting with their own data.

**2.6 Biofeedback**
    Provides more in-depth information about body, usually HR data.

**3.1 Social Support (unspecified)**
    Using the messaging feature, but no mention of cheers and taunts.

**3.2 Social Support (practical)**
    Helping others understand how to get more steps.
    Helping others by being active together.
    Helping others by purchasing or recommending they buy Fitbits.
    Checking in on others

**3.3 Social Support (emotional)**
    Using "cheers" and "taunts" in the messaging feature and/or in challenges.

**4.2 Information About Antecedents**
    Individuals create knowledge about what impacts their behavior. Most often this is in relation to physical environment, work sedentary behavior, and/or weather.

**6.2 Social Comparison**
    Weekly Rankings and/or Weekly Challenges

**7.1 Prompt/Cue**
    A notification to prompt behavior.

**8.2 Behavior Substitution**
    Individual replaces sedentary behavior with active behavior as captured by Fitbit.

**8.3 Habit Formation**
    Individual creates a habit of activity based on being active, walking, exercise, that is captured by the fitbit.

**8.4 Habit Reversal**
    Fitbit use, activity, prompts a regular and consistent active choice over a sedentary choice.

**8.5 Overcorrection**
    Attempting to go farther to meet goals because of "low" days.

**8.7 Graded Tasks**
    Badges for increased behavior
    OR
    user directed goal increases once goals are met for a period of time

**9.3 Comparative Imagining of Future Outcomes**
    Individual is prompted to engage in behavior because they think of the effect of participating in the future.
    Can be related to challenges, self-thought, etc.

**10.3 Non-Specific Reward**
    A notification that a goal has been met with a congratulations or other positive message.

**10.6 Non-Specific Incentive**
    Points or other incentive is promised to individual as a result of doing some activity. (two participants mention using Walkadoo for getting points)

**10.9 Self-Reward**
    Individual induced self-praise after meeting goal or pariticpating in exceptional behavior.

**10.10 Reward (outcome)**
    **Not sure if this counts for daily step goals** If you meet a daily step goal, is that an outcome or a behavior?

**10.11 Future Punishment**
    Individual mentions the idea of a future punishment, such as the weekly email "frowny face", as something that impacts their behavior/experience.

**11.3 Conserving mental resources**
    Individual creates mental models of exercise based on data and exprience with the Fitbit.

**12.1 Restructuring the Physical Environment**
    Individual seeks out new or different environments in order to remain physically active when normal environment or patterns are disrupted.

**12.2 Restructuring the Social Environment**
    Individual changes their socail interactions or the methods around social environment to influence behavior.
        - change fitbit cases to be comfortable to wear in many situations
        - set up working walking groups,

**13.2 Framing/Reframing**
    Individual changes their perspective on being physically active, what it takes to get activity, or their own behavior.

**13.3 Incompatible Beliefs**
    Individual is faced with information that is counter to their previously held self-image. This creates discomfort (cognitive dissonance)

**13.4 Valued Self-Identity**


**13.5 Identity Associated with Changed Behavior**
    Individual identifies themselves as someone active and/or healthy, which is different from their previous identification.

**15.1 Verbal Persuasion about Ability**
    Individual uses self-directed messaging about their ability to engage in physical activity. Most commonly used with historical data and 15.3 Focus on Past Success.

**15.3 Focus on Past Sucess**
    Exploring historical data to understand when goals were met and/or high activity days.

**15.4 Self-Talk**
    Individual uses positive self-talk to describe their activity behavior.
