P10: It tells me, with enough trust, the truth about what I'm doing.

p9: I feel like it's more seeing the positives than the hassle of walking, which I don't see as a hassle any more. I think that is because of Fitbit.

p9: Lots of other things changed in my life. At the same time I feel like, over time, even just wearing an exercise tracking device on your wrist every day, it makes you think about it a lot.
Even if I hadn't made the change yet, it just makes me think about it more than I would and reminds me, "Yes, [Margaret], this is something you care about."

p7: People always say, "Oh, sitting is really bad for your health." I was, "Yeah, yeah, yeah, whatever. I should get up and walk more. Definitely got to walk. Yeah, I should get a treadmill desk. I have nowhere to put it, but yeah, yeah." It was the Fitbit that actually made the difference.

p2: At my job, we invest in companies. If you ask me for stats and facts about one of the companies we invested in, I could give you way more stats and facts about one of those companies than I could about myself. It seems inherently wrong.

p5: I've definitely learned that I do not take as many steps as I thought I did before having a Fitbit. I remember being really confident when I first got my Fitbit, because I was a teacher so I was like, "Great. I'm not sitting at my cubicle all day. I'm up in the classroom, standing in front of kids, walking around the classroom.
I'm going to have crazy numbers. I'm going to be killing it with all friends and family. I'm a teacher, you know? This will be great."
I think after looking at the data such as at the first couple of months that I had a Fitbit, it was a shock that unless you're going to the gym. Your numbers are not very high just on walking to the car, and walking into a classroom, and moving around a campus, and getting back home.
It's really not a lot of steps for the entire day. I think that probably really surprised me the most, that you really have to be focused on the movement, and you have to have a purpose.

p9: I am a big believer of the value in data for understanding yourself and the world better.

p10: It's funny to think about the role, your Fitbit plays. It's more just a supportive thing. It's there if I'm wearing it. It tells me, with enough trust, the truth about what I'm doing.

p11: But knowing that having a source of data that you're looking at is motivating. Just measure it, just the act of having a system to track and measure and building awareness of that information, changes behavior without question.

p20: It's like a game. It's like you're getting credit for something. A lot of exercise, aside from your actual weight, it's not always tangible. Being able to look at my records and see how I improved in this area or that area is something that's...I'm a stats guy, so those kinds of things appeal to me.

 p20: Yeah, definitely. It's at least a reminder. I think about it. Every time I see my Fitbit, I think of my activity. I associate it with it. I definitely love having it on, like I feel a little bit upset, honestly, when I realize that I left it at home whenever I do leave it at home.

#### about creating mental models of what counts for steps ####
p22: Just looking at the steps, and then sometimes if it's super low, I'll be like, "Oh, let's go walk around the building." I'll take one lap around the building, but it's only 500 steps, so I'm like, "Ugh, let's take two laps then," because I've mapped out different routes around my office, and I'll know how many steps it is from point A to point B, just so I can up that number.
Interviewer:  Got you. How long did it take you to figure that out?
P22:  When we moved into this building I had that figured out within about a couple of weeks.


p25: I feel a sense of pride when I look at it. I'm like, "Yeah, I did that," and now it's in the books.

p25: We'll usually start with, "Are you gyming tonight?" I'll be like, "Man, I have to. I need more steps."

P7: I've had that for years, and I always ignore it. It comes up and says, "Time for you to break," and I go, "Yeah, yeah." I hit dismiss. I've been doing that for years. There's always been that knowledge that I need to get up and move [laughs] .
But when I'm working there's the tune like, "I'm working. I can't stop now, because I'm working." I dismiss it, but with the Fitbit I was thinking, "Oh, I wonder if it will make me get up and move more," and it did.

P9: For now, it's more just when I'm walking around and probably not driving. Driving is the enemy of walking.

p12: Going for a walk, especially when I first got the Fitbit I'd do the classics, walk around my apartment and set goals until I reached 10,000. *in response to doing things to mee their goal at the end of the day*

p13:  I think I appreciate walking more. It wasn't something that I considered before having the Fitbit, but now that I have it. I do take it more seriously and fit it more into my daily routine.

P14: When I first got my Fitbit, and I had two buddies that got theirs, and we got extremely competitive with it to the point where we were getting shin splints and stuff.

p16: for me, tracking my weight, and tracking my food, and tracking my activity provides me a measurable way that I can keep my weight under control, which has been a hard thing for me in the past.

p17: My one friend invited us to brunch at her house, and her house happened to be a mile from the bus stop. I texted her saying, "Hey, I just got to the bus stop. I'm walking to your house."
She apparently looked up on Fitbit and decided I had more steps than her and sent her husband to pick me up so that I would have fewer steps. It's ridiculous and absurd.

p17: My one friend invited us to brunch at her house, and her house happened to be a mile from the bus stop. I texted her saying, "Hey, I just got to the bus stop. I'm walking to your house."
She apparently looked up on Fitbit and decided I had more steps than her and sent her husband to pick me up so that I would have fewer steps. It's ridiculous and absurd.

p18: I'm exercising consciously, and I'm eating consciously. Tracking it helps me be conscious. That's probably the biggest benefit to the tracking component to me, not looking things up, but being very conscious of what I'm eating.

p18: Then when I do travel or I'm in a hotel or in an office building I do make a point of taking stairs and I've hit...my highest was 38 floors one day.
Interviewer:  Was that just at a hotel going up and down?
P18:  Actually that was at a hotel but there was an adjacent park on some cliffs by the beach in California, Data Point. I went up and down those damn 211 steps many times.
[laughter]
Interviewer:  I have to ask, did you count the steps or how did you know there was 211?
P18:  I counted.

p18: They're important to me, as I am a data guy and I want metrics for what I'm doing, not just a vague notion that I'm doing enough or eating right. The measurements, the outcomes that I can actually tangibly touch and feel are really important to me. What the goal is, whether it's 10,000 or 6,000 or 20,000 isn't so important as long as I'm continuing to stretch, improve, and maintain what I'm going for here. That works for me, it might not for the next person.

p20: It's at least a reminder. I think about it. Every time I see my Fitbit, I think of my activity. I associate it with it. I definitely love having it on, like I feel a little bit upset, honestly, when I realize that I left it at home whenever I do leave it at home. I think that tells me that it's important to me.

p21: Even though I can be not very active sometimes I can be very competitive, so if I know that I'm being compared to other people, then that definitely motivates me more. I find it motivating.I know I definitely put the extra effort in to walk more, because I knew other people would be checking it.

p21:  we get home late at night, so I don't want to walk all around. But there's like a particular light post that I'll walk to that isn't too far. That's about 600 steps walking to it. So I figured out OK, I know that if I walk there and back, I can get 1,200. If I know that will put me over the mark, then I'll usually do that.

p21: Which isn't something that I would have done before I got it. I obviously wouldn't have called them and been like, "Hey, what did you do today?" I notice that. They do it, too. More between me and my dad. My mom is along for the ride. Me and my dad will definitely...He'll do the same thing. If he knows that he got a lot of steps one day, he'll either taunt me on the website, or he'll send me a text message, like, "Oh, I got this many steps today." It definitely has made us more aware.


p23: I wish there was some kind of magic way, or some sort of device like the Fitbit, and maybe it has been for people ‑‑ actually I know it has been for...I talked to people about it ‑‑ to really change their routine, and their lifestyle, and get them to be more active health focused. For me personally it has not. In retrospect, I'm not sure if I would buy one again. I feel bad about that because I was pretty excited about when I first started with it.

p25: Being active isn't a thing that you compartmentalize into an hour of doing one type of exercise. What it's taught me is that I need to be moving throughout the day. I park farther than I used to. I always take the stairs. Little things that before I thought was just crazy. I'm going to go to the gym later, what do I care if I'm going to take the elevator? Whereas now it's like, no, I'm going to get like two flights of stairs out of this.
