---
title: "Background & Significance"
author: "Ernesto Ramirez"
date: "March 1, 2016"
output:
  word_document:
csl: apa-no-ampersand.csl
bibliography: library.bib
---
# Background & Significance

## Physical Activity & Public Health
Since the seminal work of Morris and colleagues in the early 1950's that examined the relationship between work-related physical activity and coronary heart disease, public health officials and researchers have extolled the benefits of leading an active lifestyle [@Morris1953]. Over the last six decades, numerous studies have examined the link between physical activity and health. At one end, a number of prospective studies have shown a indicated that there is a significant increase in the relative risk of all cause and specific cause mortality associated with living a physically inactive lifestyle for adult men and women [@Nocon2008; @Oguma2002; @Paffenbarger1986a; @Simonsick1993]. The first Surgeon General's report on Physical Activity and Health, released in 1996, emphasized the role of physical activity as a preventative health behavior, especially the importance of including moderate levels of activity [@SurgeonGeneral1996]. This report, along with many systematic and narrative reviews, have concluded that there is compelling evidence that pariticipating in regular physical activity is related to reductions in the risk of cardiovascular dieases (including coronary heart disease and hypertension), obesity, osteoperosis, type 2 diabetes, and certain types of cancer [@Bauman2004; @Kokkinos2011; @Warburton2006]. Physical activity has also been shown to have protective effects for mental health [@Bauman2004; @Penedo2005].

Furthermore, there is an abundance of evidence indicating that an inverse dose-response relationship exists between physical activity and cardiovascular health, among other health conditions, and that ignificant improvements in health occur when individuals move from being inactive (and least fit) to being active (and improving physical fitness) [@Blair1989a; @Lee2001; @Li2016; @Thune2001; @Warburton2006]. The 1996 Surgeon General's report found that participating in a moderate amount of activity, equivilant to 30 minutes of brisk walking per day (150 kcal/day), was associated with "substantial health benefits", and that for those already meeting this threshold, additional phsyical activity may experience additional health benefits [@SurgeonGeneral1996]. These findings were echoed in the release of the 2008 Physical Activity Guidelines for Americans.


### Physical Activity Guidelines - United States
In 2008 the U.S. Department of Health and Human Services published the Physical Activity Guidelines for Americans based on the available literature and insight from the 13-member Physical Activity Guidelines Advisory Committee. These guidelines offer separate recommendations based on age (youth, adults, and elderly), and on the type (strength vs. aerobic) and intensity of exercise (moderate vs. vigorous) [@PAGuidelines2008]. For adults, the guidelines recommend:

+ At least two days a week of muscle-strengthing activities

plus one of the following:

+ 150 minutes per week of moderate-intensity physical activity,
+ 75 mnuntes per week of vigorous-intensity physical activity
+ or any equivilant combination of moderate-to-vigorous physical activity

The guidelines also state that additional health benefits are observed for indiviudals who increase moderate-intensity activity to 300 minutes per week, and/or increase vigorous-intensity activity to 150 minutes per week. The guidelines further eloborate on how an individual may acquire the weekly amount of activity, stating that moderate or vigorous activity must occur for at least 10 consecutive minutes and that total activity should be spread throughout the week.

These guidelines are based on the recommendations of the Physical Activity Guidelines Advisory Committee who found in their research that "a range of 500 to 1,000 MET-minutes of activity per week provides substantial benefit" and sought to translate this into something "useful for the public." [@PAGuidelines2008, Appendix 1]. The 150 minutes of moderate-intensity activity is a translation of 500 MET-minutes, where moderate activity is classified as 3.0 to 5.9 METs. Specifically, a brisk walk at 3.0 MPH requires 3.3 METs and 150 minutes of walking at 3.0 MPH is approximately equal to 500 MET-minutes. This same rationale was used to create the lower limit for vigorous activity, where vigorous-intensity activitiy is classified as greater than or equal to 6.0 METs.

### Prevalence of Physical Activity - United States
While the above mentioned guidelines give the general public concrete goals to reach for weekly physcial activity, the results of these and similar published guidelines has been less that favorable. A large proportion of the population continues to lead primarily inactive lives. According to objective accelerometer data from the 2003-04 National Health and Nutrition Examination Survey (NHANES) approximately 95% of adults (over 19 yrs) did achieve at least 30 minutes of moderate-intensity activity on five of seven days [@Troiano2008]. Tucker, Welk, and Beyler [-@Tucker2011] conducted a similar analysis based on 2005-06 NHANES accelerometer data and the 2008 Physical Activity Guidelines for Americans. They found that only 9.5% of men and 7.0% of women were meeting the guidelines. Data from the National Health Interview Survey, found that among adults self-reporting their physical activity behavior, 21.4% met the physical activity guidelines [@NHIS2014]. Low levels of physical activity has also been directly associated with a signficicant financial burden on the Unites States healthcare system. Carlson and colleagues [-@Carlson2015] found that even after adjusting for individuals who could have difficulty participating in regular physical activity, low levels of physical activity was associated with approximately 9% of aggregate healthcare expenditures.

Current estimates of the type of physical activity that adults most engage in are derived from self-report. Data from the 2011 Behavioral Risk Factor Surveillance System was analyzed and walking was by found to be the most commonly reported, with 47% of adults reporting walking for aerobic physical activity [@Watson2015]. Walking remained consistently high when compared to other activities across age groups, with only 19-29 year olds reporting walking as the second most popular activity to running/jogging. For all age groups, running/jogging was reported as the second most common (13%) followed by lawn and garden activities (10%), sports (9%), and conditioning exercises (9%). The findings are important as they may help public health official create tailored messages that "meet people where they are" as well as guide the use of measurement tools that accurately capture the most common activities.

## Measuring Physical Activity
The measurement of movement can be understood through two dimensions as demonstrated by LaMonte and Ainsworth: physical activity expressed as an observed behavior, and energy expenditure expressed as the observed energy cost of the behavior[-LaMonte2001]. Although these two dimensions are not synonymous, the methods employed when measuring movement often use one dimension to infer the other. The methods describes below are primarily used to collect information about physical activity through direct or indirect means in population and public health research.

### Direct Observation
The direct and systematic observation of human behavior has a long-standing history in the sciences. The systematic recoding of what people do, how they do it, and the context(s) in which the behaviors occur can provide a rich amount of data for behavioral researchers. Using various measurement systems, direct observation allows the observer to collect data about the physical activity an individual or group of individuals are participating in. This data can include the type, duration, intensity, and frequnecy of the behavior. Additionally, contextual information can also be recorded such as where the activity occurs, with whom it occurs, and other social and/or environmental information such as behavioral stimuli [@McKenzie1991b; @McKenzie2002]. A number of instruments have been designed and validated that include direct observation as a core data gathering technique. These instruments, such as the System for Observing Fitness Instruction Time (SOFIT), Sytem for Observing Play and Leisure Activity in Youth (SOPLAY), and the Chilren's Activity Rating Scale (CARS), are primarily used to assess younger populations, primarily school-age children [@McKenzie1991; @McKenzie2000; @Puhl1990]. There are tools, such as the System for Observing Play and Recreation in Communities (SOPARC) that can be used to assess physical activity in a wide range of age groups such as children, teenagers, adults, and seniors [@McKenzie2006]. Direct observation, while offering detailed information about physical activity behavior, requires a large amount of effort on the part of the research study staff, namely the time and energry spent to adequately train the observers and the time spent conducting the observations [@McKenzie2000; @McKenzie2002]. Additionally, direct observation requires access to locations in which physical activity is occuring making it prohibitively difficult to collect information regarding the full range of physical activity that happens throughout the course of a day.

### Self-Report
In order to better understand daily physical activity behaviors researchers have deployed a variety of instruments that allow individuals to report on their behavior. The use of survey tools and questionnaires has a long history in physical activity and public health research. In the late 1960's researchers began to include questions regading occupational and leisure time physical activity in their studies of mortality and heart disease [@Hammond1964; Frank1966]. This marked a new direction in measurement as previously physical activity behavior had been typically inferred through occupational information [@Haskell2012]. In the intervening half-century numerous questionnaires, guided interviews, and survey instruments have been used to assess physical activity behavior in a wide range of populations. A recent systematic review of measurement properities of physical activity questionnaires found 85 unique questionnaires (different versions of the same instrument were considered unique) [@VanPoppel2010]. The authors found that construct validity (the degree to which the instrument measures actual physical activity behavior) was evaluated for 77 questionnaires through comparisons with objective measures such as acceletometers, heart rate monitors, pedomoters, or doubly labelled water. Correlations between questionnaire outcomes and objective measures were found to be overwhelmingly low, typically lower that 0.50. This is not suprising given the limitations of self-report measures. Numerous factors, on the part of the respondent and the measure, may impact the reliability and validity of a self-report measure. For example, the complexity and overall length of a measure, the type of scale or response requried, and length of time a respondent is required to recall all impact a measure's ability to adequately assess physical activity behavior. It is also important to understand that individual and social factors, such as the ability to remember or recall behaviors or social desirability of appropriate behavior, may also influence an individual's ability to accurately report their behavior [@Shephard2003; Sallis2000b].

### Pedometers
The pedometer is relatively simple and typically inexpensive tool for measuring human locomotion. The invention of the pedometer can be traced back to Leonardo de Vinci and includes a tale of invention and re-invention by, among others, Thomas Jefferson [@Jefferson1999]. Regardless of its invention, the popularity of pedometers for measuring and displaying the number of steps an individual takes has a long history in the research literature. The first mention of the pedometer in the research literature is a letter to the editor in the December 13, 1912 edition of Science, wherein the author (identified only as T.C.M.) describes the pedometer as,

> “A most useful addition to the outfit of a traveler and an especially delightful and comforting companion to those who know the joy of seeing the world à piede.” [@T.C.M.1912]

He further explains the difference between the wrong kind of pedometer (which only counts steps) and the right kind (which counts distance). Type aside, the pedometer as a step measuring and tracking device became part of the public consciousness as a result of the widespread popularity of walking clubs in Japan. [@Tudor-Locke2004] describes a 2001 presentation at the annual meeting of the American College of Sports Medicine during which Dr. Yoshiro Hatano explained the rise in popularity of the pedometer and the now widely adopted 10,000 steps per day guideline. In the 1960’s the pedometer company, Yamasa Corportaion (which sells pedometers under the Yamax brand in the U.S.), sold a pedometer under their nickname manpo-kei, which translated means “ten thousand step meter.” [@Tudor-Locke2004; @Tudor-Locke2008].

The pedometer has been widely use a measurement tool and intervention component in physical activity and broader public health research. As a measurement tool, pedometers have been used to measure and track steps as a representation of daily physical activity in children and adults beginning in the early 1990s [@Bassett1996; @Tryon1991]. Different types of pedometers have been used literature as various models and brands have been shown to be accurate and reliable. As an intervention tool, pedometers have been described as:

> “a tracking device (continuously collecting current activity), a feedback tool (providing immediate information on activity level), and as an environmental cue (reminder to be active). Used in combination with record keeping (e.g., calendars or diaries of daily progress), pedometers may be used in an effective way to increase daily physical activity.” [@Tudor-Locke2002]

According to a systematic review, the use of pedometers was associated with an increase of 2,491 steps per day for adults engaged in randomized controlled trials, and 2,183 steps per day for adults enrolled in observational studies. Across all study types the authors also found that pedometer use was associated with significant reductions in body mass index [@Bravata2007b]. Why do pedometers increase physical activity? The following are adapted from Tudor-Locke & Lutes [-@Tudor-Locke2009a]:
1.	“Pedometers offer a simple estimate of physical activity volume in terms of steps taken. This uncomplicated and straightforward output it a direct indicator of movement as a result of behavioral choices.” (pg. 983) - Pedometer are easy to understand and the information is a direct reflection of real-world behavior.
2.	The information is personal and meaningful because it is about the user.
3.	Inherent, immediate visual feedback offers “instantaneous awareness to the end-use that can be directly acted upon.” The information is available in real-time and an individual is able to see the effect of choice and actions on the outcome.
4.	The ability to check one’s progress in real-time is useful for setting goals, and checking and evaluating progress.
5.	Recoding, storing, interacting with, and visualizing pedometer data provides additional mechanisms for personalized feedback, and a deeper understanding of behavior patterns.
6.	The ability to transfer data and share it with others introduces social constructs such as accountability, support, comparison, and competition.

### Accelerometers
Accelerometers are usually small microchips that contain systems for measuring the gravitational force (g-force) acting on the device. Typically, accelerometers measure g-force along a given axis. Accelerometers are used in combination with microprocessors and digital memory storage. These microprocessors interpret the g-force readings supplied by the accelerometer and save it to the digital memory. In 1983, researchers tested a newly designed uni-axial accelerometer intended to measure vertical displacement during human movement when worn on the hip and found the accelerometer ouput to be correlated (r = 0.74) with oxygen uptake during a variety of exercises [@Montoye1983]. Since then, accelerometers have become one of, if not the most, common objective measurement tool for assessing physical activity, with over 600 research articles mentioning accelerometery and physical activity in 2012 and 2013 [@Troiano2014a]. Current accelerometers feature sensors that can measure acceleration along three axis to better interpret and classify the frequency and intensity of physical activity as well as improved memory storage and battery life.

Accelerometers typically produce outputs in "counts per epoch", and these counts are then translated into biological constructs such as time spent in different activity intensity categories (some accelerometer also genreate behavioral data such as steps). Numerous equations exist for translating the outputs from different accelerometer models into energy expenditure values and time spent at different activity intensities [@Matthew2005]. Overall, accelemeters, and the various methods for interpreting their outputs, have been found to reliable and valid for measuring physical activity in children, adults, and older adults [@Berlin2006]. New technological advancements and statistical methods have combined in recent years to improve activity recognition and energy expenditure estimation in accelerometers-based studies of phyiscal activity. It should be noted that accelerometers are not without limitations. Obtaining an apropriate measurement period in free-living conditions can be problematic as participants have been known to object to wearing the device on a waistbelt or waist clip due to discomfort [@Troiano2014a].

### Behavioral Self-Monitoring
> “People cannot influence their own motivations and actions very well if that cannot pay adequate attention to their own performance, the consequences under which they occur, and the immediate and distal effects they produce.” [@Bandura1991, p. 250]

Behavioral self-monitoring, observing and recording one’s own behavior(s), has long been identified as a key piece of various theoretical models of behavior. Self-monitoring, originally designed as a method for obtaining data and insight about behavior which was only observable by the individual (and not by a therapist or interventionist) has also been identified as worthwhile intervention technique in health behavior program design and research. Self-monitoring is thought to be an effective method of engaging individuals in their health behavior because of reactive effects, evaluative effects, and it’s influence on self-regulatory mechanisms.

Self-monitoring has a rich history in the therapeutic and behavioral psychology literature. Self monitoring is effective for prompting behavior change and is used by over 80% of cognitive and behavioral therapists [@Elliott1996; Korotitsch1999; @Olson2008]. Dating back to the 1970’s researchers and clinicians have been debating about how self-monitoring interacts with changes in human behavior. In the 1970s, Kanfer described self-monitoring as being composed of three distinct and ordered processes related to self-directed behavior change: self-monitoring, self-evaluation, and self-reinforcement or punishment. Self-monitoring is simply the act of observation and recording of the behavior of interest. Self-evaluation is the act of comparing the observed and recorded information against a self-selected criterion or goal. Lastly, self-reinforcement or punishment is the “motivational” component during which self-selected internal or external rewards are introduced (when observed behavior meets or exceed the criterion) or internal or external negative consequences are realized (i.e. punishment, when observed behavior does not meet the criterion [@Kanfer1970].

In his work on developing Social Cognitive Theory, Albert Bandura emphasized the role of self-monitoring as a primary sub-function of self-regulatory processes. In contrast to the earlier characterization by Kanfer, Bandura describes self-monitoring as “not simply a mechanical audit of one’s performances.” In addition to the regulatory actions of criterion formation and evaluation, Bandura proposed additional domains in which we can understand how engaging in self-monitoring can impact behavior. These include, the self-diagnostic and self-motivating functions, temporal proximity, informativeness, motivational level, behavior valence, and orientation to self-monitoring [@Bandura1991, p. 250]. Bandura describes the cognitive self-regulatory processes of self-observation, judgment, and self-reaction, suggesting that interactions between these processes create the locus of self-regulated motivation. Bandura proposed that the locus of self-regulated motivation is observed discrepancies between current behavior and personal or social standards. Bandura also suggests that self-efficacy predicts cognitive self-regulation, and that reducing the discrepancies between current behaviors and personal or social standards can enhance self-efficacy. Physical activity tracking devices and applications generate motivating discrepancies and have the potential to improve self-efficacy through prominent features such as goal setting, feedback on the gaps between personal goals and current behaviors, and feedback comparing personal behavior to behavioral norms of social groups.

As with any measurement method, a premium is placed on accuracy. Korotitsch and Nelson-Gray [-@Korotitsch1999] identified nine variables that may affect the accuracy of the self-monitored data: 1) Awareness of accuracy checks, 2) Topography of the target behavior 3) Training, 4) Compliance, 5) Reinforcement, 6) Nature of the recording device, 7) Concurrent response requirements, 8) Valence of the target behavior and, 9) Timing of recordings. Furthermore, Korotitsch and Nelson-Gray  identified several techniques that can increase compliance, such as verbal commitments, frequent prompts or reminders, and monetary incentives. Both compliance and accuracy affect the degree to which self-monitoring is effective for inducing behavior change. Olson et al. [-@Olson2011] found that offering individuals a choice in target behavior, as opposed to prescribing a specific behavior, resulted in increased compliance with self-monitoring activities and self-reported levels of behavior change. Foster et al. [-@Foster1999] also indicated that issues related to compliance with data collection, data quality, and the burden or participation in self-monitoring research are important areas of exploration in this field of study.

Self-monitoring has been shown to have an impact on behavior even when additional intervention methods or tools do not accompany it. For example, self-monitoring has been found to be an effect method for improving diet and weight, physical activity, and diabetes control. In fact, self-monitoring has been described as a “key strategy” for long-term weight loss by researches examining the behaviors of participants in the National Weight Control Registry. A meta-analysis of behavior change techniques for healthy eating and physical activity identified self-monitoring as the technique that explains the greatest amount of heterogeneity in the included studies, indicating it’s value and importance for improving effectiveness of health behavior interventions [@Michie2009].

## The New Age of Self-Monitoring
In 2008, Gary Wolf and Kevin Kelly held the first Quantified Self meetup where approximately 30 individuals gathered to share stories about how they were using technological methods and tools to track, measure, analyze, and understand their lives [@Ferris2016]. In 2010 Wolf wrote what is consider the definite account of the creation and rational behind the Quantified Self phenomenon. In his article, he places the history of self-monitoring in historical and present context, noting that prior to recent changes most monitoring was done by hand and required using laborious methods to infer meaning.

> “Then four things changed. First, electronic sensors got smaller and better. Second, people started carrying powerful computing devices, typically disguised as mobile phones. Third, social media made it seem normal to share everything. And fourth, we began to get an inkling of the rise of a global superintelligence known as the cloud.” [@Wolf2010]

These four changes to our personal interactions with technology have caused a wide-spread increase the availability and use of devices, applications, and tools that have quickly overtaken the “by hand” method of self-monitoring and self-collected data gathering. For instance there are over 60 wrist-worn devices that can track data related to physical activity including heart rate, skin temperature, and skin conductivity [@Ramirez2014]. Individuals can use their smart phones to track their location and activity at high fidelity by using applications that gather and process signals from the many onboard sensors (i.e. accelerometer, gyroscope, and GPS). The popularity of self-tracking in and outside the physical activity domain has been increasing over time. In the 2013 report, Tracking for Health, the Pew Research Center’s Internet and Life Project found that nearly 70% of adults track at least one health indicator for themselves or others. Of those who track, 21% track with technology [@Fox2013].

### Who's Using Wearables?
Current estimations of the prevelance of wearable device use are primarily derived from marketing firms and industry reports. These reports use a variety of survey methods, typically online or via phone call, to generate data on the number of individuals using "wearables" or "activity trackers." In late 2013 Endeavor Partners conducted a survey  of "thousand of Americans" and found that 10% owned an activity tracker of some kind. They also found that 50% of individuals who have owned an activity tracker no longer use it and one third stopped using it within six months [@Ledger2014]. In mid-2014 Endeavor released an update to their findings based on newly aquired survey data. They found that the percentage of adult consumers that still wore and used their activity tracker had improved with 88% still wearing it after three months, 77% after 3–6 months, 66% after 6–13 months, and 65% after a year [@Ledger2]. A global survey conducted by Accenture in the fall of 2014 found that 8% of individuals (ages 11-55) owned a wearable fitness monitor and 6% owned a wearable health device [@Accenture2014]. Another survey, conducted by Rocket Fuel in late 2014, of 2,245 US adults found that 16% of US consumers use a wearable health and fitness trackign device [@RocketFuel]. Recently, Accenture updated their findings based on an online survey of 8,000 consumers across seven countires (2,225 in the US) conducted in December 2015 and January 2016. They found that wearable use had more than doubled, to 21% [@Accenture2016]. The findings of these surveys, while encouraging to those who make and market wearable devices must be taken with caution. In nearly all cases, the survey methodology, questions, and even the participant characteristics are excluded from the reports.

## Fitbit Physical Activity Trackers
In September 2008, the first verstion of the Fitbit activity tracker was unveiled at the TechCrunch50 Conference. At the time, it was described as "a small, wireless device, the size of a thumb" that used a tri-axial accelerometer to measure and track steps, distance, energy expenditure, and sleep [@Miller2008]. The first Fitbit devices were distributed on year later in the fall of 2009 to its first customers, and cost $99. The initial device included a "base station" that combined wireless data transfer and battery charging (when the device was connected to the base station). The battery lasted for approximately seven days, and the device would sync with the user's online account whenever it was in range of a base station connected to a internet-conected computer. The device itself included a LED screen and a physical button. By pushing the button a user was able to cycle through the data the device had captured for the current day including: steps, distance traveled, energy expenditure (calories burned), and a flower icon that grows (or shrinks) according to activity levels over the last three hours [@FitbitManual].

[FIGURE TK. FITBIT & BASE STATION]

Since 2009 Fitbit, Inc. has released an additional ten tracking devices of which 8 are currently available for purchase (see Table TK for a description of all devices - TABLE FITBITDEVICES). Each of these devices, whether worn as a clip or on the wrist, are based on a tri-axial accelerometer and proprietary data processing algorithms.

## Fitbit Market Estimation
Fitbit has established itself as the market leader in this activity tracker space with an estimated 26.9% market share for wearables worldwide [@IDC2016], which includes devices such as connected smartwatches. More specifically, the NPD Group found that Fitbit accounted for 79% of the sales for connected activity trackers in 2015 [@NPD2016]. In May, 2015 Fitbit registered with the Security and Exchange Commission (SEC) for an initial public offering. In their filing documentation they disclosed the volume of their sales since 2009, when the original Fitbit tracker was released. Sales of devices per year has risen steady, from almost six thousand devices in 2009 to 21.4 million in 2015 [@FitbitSEC, @Fitbit2015]. It is important to note that the number of devices sold may not accurately reflect the number of individuals using a device. In their SEC filing Fitbit released the number of "paid active users":

> We define a paid active user as a registered Fitbit user who, within the three months prior to the date of measurement, has (a) an active Fitbit Premium or FitStar subscription, (b) paired a health and fitness tracker or Aria scale with his or her Fitbit account, or (c) logged at least 100 steps with a health and fitness tracker or a weight measurement using an Aria scale. The number of paid active users is based on subscription and device activity associated with each Fitbit user account and, accordingly, a user with multiple devices synced to his or her Fitbit account is counted as only one paid active user regardless of the number of devices that such user syncs to the account. [@FitbitSEC, pg. 57]

Paid active users increased each year it has been reported, from 558 thousand in 2012 to 16.9 million in 2015. Overall, the United States is currently the largest consumer of Fitbit devices, comprising 74% of Fitbit's 2015 revenue [@Fitbit2015]. As Fitbit has been widely adopted as a method for personal physical activity measurement, their has been considerable interest from the research community for understanding it's utility as both a measurement tool and intervention component.

## Validity
To date, Fitbit has not publically released any information related to the accuracy of their different devices. They indicate, on a webpage addressing accuracy concerns, that they have "performed multiple internal studies to rigorously test the accuracy of Fitbit trackers." and that their testing has "confirmed that our trackers are some of the most accurate wireless tracking devices.", however none of these studies are available to the general public or research community [@FitbitAccuracy].

 The author, in conjunction with collaborators at the Center for Wireless and Population Health Studies and the Department of Computer Science, has examined the validity of the Fitbit Ulta in 2012. In one study of 17 adults we found evidence indicating the Fitbit Ultra performs adequately for structured activities in outdoor and laboratory environments. The magnitude of the difference between the Fitbit and direct observation of step counts (M(SD); range) was small across all activities when worn on the waist (2.0%(4.7%); -6 – 23%) and the bra (0.8%(4.3%); -11 – 15%). A significant effect for speed was found indicating that at higher locomotor speeds (e.g. jogging) the Fitbit underestimates the number of steps taken [@ramirez2012]. Since 2012, a number of studies have examined the validity and reliability of various Fitbit devices. Everson, Goto, and Furberg [-@Evenson2015] recently published a systematic review of the validity and reliability of activity trackers, including Fitbit. They  identified 22 studies published since 2012 that examined the validity and/or reliabilty of the data captured by one or several of the six following Fitbit devices: the Fitbit Classic (original), Fitbit Ultra, Fitbit One, Fitbit Zip, and Fitbit Flex. Twelve studies examined the validity of reported steps for Fitbit devices. Overall, steps reported by Fitbits worn at the waist (Classic, Ultra, One, and Zip) were highly correlated (>= .80) with direct observation and validated measurement tools such as the Yamax CW-700 pedometer and Actigraph GT3X accelerometer. The Fitbit Flex, which is worn at the wrist was found to slighly less accurate. One study examined the validity of the reported distance by the Fitbit One, and it was found to overestimate distance at slow speeds and overestimate at fast speeds. It should be noted that Fitbit recommends calbrating the user's actual stride length to achieve optimal distance measurement for walking and running [@FitbitStride2016]. Fitbit also reports minutes in four activity intensity categories (sedentary, lightly active, farily active, very activty). When compared to established cutpoints for research accelerometers, there does not appear to be a consensus on how accurate these measurements are. One study reported a very high correlation for the Fitbit Zip, while a second study reported low aggreement for both the Zip and One. Lastly, for energy expenditure, across seven studies the Classic, Ultra, Zip, One, and Flex tended to underreport total energy expenditure.

## Reliability
Everson and colleagues located seven studies that examined interdevice reliability of Fitbit devices. That is, studies examining reliabilty only examined multiple similar devices and/or location placement, but did not test wheter a single device remained reliable under consistent conditions. For steps, the Classic, Ultra, One, and Flex showed high reliability for walking and running. Reliability was also very high for different trackers (of the same type) and wearing in different locations (hip vs. pocket or different wrists) for both distance (one study) and energy expenditure (two studies).

Overall the authors conlcuded that for the tested devices there is high validity for steps, and high interdevice reliability for steps and energy expenditure. It should be noted that to-date no validity or reliability studies have been published for the physical activity tracking abilities of the Fitbit Force (recalled), Fitbit Charge, Fitbit Charge HR, or Fitbit Surge.

## Interventions
Fitbits have been used in a variety of different physcial activity intervention studies. In these studies the Fitbit has been deployed as a measurement device for the outcome of interest as an active component of the intervention, or a combination of the two. As a measurement device, the Fitbit has been used in a series of studies to examine the impact of different types of percentile feedback and reinforcement schedules on daily steps counts in adults [Kurti2013; Washington2014]. These studies restricted participant's use of the full Fitbit system (website and mobile applications) in order to reduce the potential influence of the behavioral components. More recently, Cadmus-Bertram and colleagues [-@Cadmus-Bertram2015a] examined the feasibilty of using a Fitbit One for continuous monitoring and found that adult women adhered to wearing the Fitbit with a median weatime of 10hrs per day during the 16-week physical activity intervention. This finding was similar to what was observed in an intervention trial with 29 inactive pregnant women using the Fitbit Ultra who wore it approximately 80% of the time during a 12-week study [@Choi2015].

There is some evidence that the Fitbit alone can be used to improve physical activity behavior. In a randomized control trial, women using the Fitbit system (Fitbit One and the Fitbit website) were observered to have significant increases weekly MVPA, MVPA bouts, and steps per day when compared to the control group who used a simple pedometer [@Cadmus-Bertram2015]. However, Thorndike et al. [-@Thorndike2014] found that the Fitbit alone was not sufficient to improve physical activity behavior among medical residents in a randomized controlled trial.

Researchers ahve also have deployed additional behavioral components with the Fitbit device and/or full Fitbit system in order to undersand what complimentary intervention techniques might be useful for improving physical activity. Fitbits, in addition to a mechanisms for feedback, goal-setting, and reinforcement through rewards, were found to improve physical activity during recess in small trial of six elementary students [@Hayes2015]. In adults, the addition of text-messaging prompts did not have an impact on physical activity behavior of those using and wearing Fitbit One devices [@Wang2015]. In older adults (65 - 95 years old), a combination of the Fibit and phone-based and in-person physical activity counseling to did not improve physical activity in a randomized controlled crossover study [@Thompson2014]. A small study of seven overweight adults found support partial support for the Fitbit One as a postive influencer of physical activity behavior. The addition of behavioral coaching, which included tailored feedback, personalized goal-setting, behavioral reccomendations, and social support, further improved activity outcomes [@Valbuena2013]. In a trial of cardiac telerehabiliation adults were asked to use a Fitbit Zip for a minimum of three months and maximum of one year. Across the 64 participant the average Fitbit use was 160 days, with a trend for improved walking behavior (steps per day) associated with longer device use [@Thorup2016].

These intervention studies represent a small piece of the growing interest in using commerical activity monitors in clinical research. A recent search of the ClincalTrials.gov database by journalists at MobiHealthNews.com uncovered 21 registered clinical trials that include a Fitbit device in their research design [@Comstock2016]. It would be safe to assume that the number of researcher trials using Fitbit devices will continue to grow as Fitbit, Inc introduces new devices and improvements in software.

## Behavior Change Techniques
Interventions that positively impact health behaviors, especially physical activity and weight loss associated behaviors, are more efficacious when they employ theoretically driven approaches. Recently, there has been a shift toward more specifically identifying the individual components in interventions in a trans-theoretical approach [@Abraham2008; @Michie2011a]. This new area of research focuses on the specific techniques employed by behavior change interventions (behavior change techniques, BCTs). Michie and colleagues [-@Michie2013] have defined BCTS as having the following eight characteristics:
1. They aim to change behavior.
2. They are the "active ingredients" of the intervention.
3. They are smallest components of the active ingredients.
4. Are used by themselves or in combination with each other.
5. Are both observable and replicable.
6. They can have measureable effect on behavior.
7. May or may not be supported by the literature.
8. May be self-delivered, or by another individual (process).

The current verison of the Behavior Change Technique Taxonomy (BCTTv1) was developed through an iterative proccess that involved multiple studies and over 400 behavior change experts and researchers [@Michie2015]. This process identified 16 domains, which encompass 93 unique techniques that have been employed in health behavior change interventions (see Table TK).

These behavior change techniques (BCTs) can be used for intervention planning and system or program assessment. For instance, a refined BCT taxonomy has been used to assess mobile health applications, wearable physical activity trackers, and internet-based program for physical activity and weight loss [@Chen2015; @Cowan2013; @Conroy2014; @Lyons2014; @Dennison2013a; @Pagoto2013a; @Yang2015a]. This assessment work is vital as the use of BCTs has been directly associated with behavioral improvement, and this association follows a dose-response relationship. A review and meta-analysis on internet-based health has indicated that interventions that use more BCTs have larger effects on behavior than interventions that used fewer techniques [@Webb2010b].

The current understanding of the impact of BCTs on health behavior is guided by rigorous reviews and post-hoc evaluations of reported intervention components. For instance, Michie and colleagues found that physical activity and diet interventions that include self-monitoring (an identified BCT) and at least one other BCT were more effective than interventions that did not include self-monitoring [@Michie2009]. As the lay population have rapidly adopted commercial health behavior tracking and behavior change tools, researchers have begun to evaluate these tools through the lens of the BCT taxonomy. These reviews typically explore the design of commercial tools/apps in order to determine if “what works” (BCTs) is included in the design of their tools. However these reviews are based on researcher’s brief experience with the app/tool, sometimes lasting as little as a few days [@Chen2015; @Cowan2013; @Conroy2014; @Lyons2014; @Dennison2013a; @Pagoto2013a; @Yang2015a]. Additionally, there appears to be an underlying belief being that BCT inclusion, and the volume of the inclusion, will have a direct positive impact on individuals who use those tools/apps.

To date, , Lyons et al. [-@Lyons2014] have conducted the only systematic analysis of commerical physical activity  monitoring systems in order to determine the BCTs that are used by the devices, mobile applications, and websites (if available). Trained coders used 13 different tracking devices for one to two weeks. One Fitbit device, the Fitbit Force and it's mobile and web-based applications, was included in the analysis. Overall, BCTs within the domains of *Goals and Planning* and *Feeback and Monitoring* were found to be the most commonly used including *goal setting (behavior)*, *discrepency between current behavior and goal*, *feedback on behavior*, and *self-monitoring of behavior*, which were observed in all systems included in the analysis. Specific to the Fitbit Force, the authors identified 20 BCTs implemented in the design of the device, mobile application (iOS/Apple only), and website. It should be noted although the focus of their analysis was on electronic activity monitors, they included aspects of the system that were not directly related to physical activity data gathering and behavior change such as weight and mood measurement. Snce this analysis was published many changes have occured that may impact these findings. In the intervening two years the Fitbit Force has been recalled and discontinued, Fitbit has released an additional five devices, and the mobile applications have undergone numerous revisions and udpates that have introduced new features.

## Current Research
In the last few years a few different disciplines have begun to engage in research on the use of new self-tracking and personal health tools and devices. Across disciplines there is an overwhelming focus on introducing these new types of tools into the lives on participants in order to understand their usability, validity, and ability to serve as intervention tools. To date, there have been few studies that have sought to examine the use of BCTs by users of self-tracking devices. The majority of studies have typically focused on usability testing (testing design characteristics), or recruit individuals to use a device for only a short period of time [@Mercer2016; @Rabin2011a; @Shih2015]. The few studies that have recruited a sample of individuals who have freely chosen to engage with self-tracking devices and/or apps have focused on a broad range of technology oriented health behavior change systems [@Gowin2015].

As stated previously, there are a large number of individuals who are using these tools on a daily basis to track, engage, and learn about their own behavior in real-time. Currently there exists a distinct lack of research that explores the “how” and “why” of physical activity tracking device use in populations that self-select to use them. In 2014 Fritz and colleagues [-@Fritz2014] conducted a qualitative inquiry to better understand how individual use different activity tracking devices, explaining their rational for the study they stated,

> “Investigating the experiences of people who have adopted these technologies “organically” and continued to use them over time offers the opportunity to study certain contexts and aspects of use not possible in shorter-term experimental deployments. It also affords the opportunity to see how findings of previous shorter studies hold over longer-term use.” (pg. 487)

Their research was based on in-person and online audio interviews of 30 participants who had been using different devices (including Fitbit, Jawbone, and the Nike Fuelband among others) for at least three months. Their chosen method of identifying and assigning open and closed codes (identified through literature review) focused on observing general themes about device use, changes in use over time, and psychosocial and behavioral aspects of use. Through the interviewing, transcription, coding, and analysis process they identified six major themes: attachment to the devices and data, awareness of self and behavior, immediate impact of data capture and reflection in real-time, motivation and reflection, meeting goals and “getting credit”, using internal and external rewards, and the use of social support and community features. These findings build on the previous qualitative work by Li, Dey, and Forlizzi [@Li2011], who interviewed 15 individuals who identified as self-trackers. These participants represented variety of data collection types including blood glucose, weight, sleep, physical activity, and productivity. The authors were able to identify six common questions that are present when people talk about their data collection and reflection processes. These six themes were: Status (“What is my current state?”), History (“What does my data indicate over a long period of time?”), Goals (“What should my goals be and how do I set them?”), Discrepancies (“How does my current status compare with my goal?”), Context (“What other information is related to my data?”), and Factors (“What changes my status over longer periods of time?”). The authors further break down the act of personal data collection into a two-phase structure: Discovery and Maintenance. The discovery phase includes individuals who are focusing on their history, goals, context, and factors. They are unclear of what they should be focusing on pertaining to goals and/or do not understand what influences their behavior. On the other hand, the maintenance phase unsurprisingly features individuals who ask themselves primarily about status and discrepancies. That is, they are attempting to maintain their behavior by using a system to consistently check themselves against their identified goal(s). These studies, two of the few that explore the real-world behavior of individuals using new digital self-monitoring tools, primarily focus on using their findings to inform the future design of similar tools.

## Summary
Engaging in regular physical activity is an important component of living a healthy life and evidence continues to build for the protective effects of physical activity for numerous health conditions. Unfortunately, the number of individuals who engage in the necessary minimum amounts of physical activity to experience these benefits remains a very low levels. Even eight years after the publication of natoinal guidelines for weekly physical activity, the vast majority (> 90%) of Americans continue to lead primarily inactive lives [@Troiano2008].

However, in the last few years there has been an exponential increase in the number of individuals who are engaging with their own physical activity behavior through various different physical activity tracking devices. Millions of individuals are using Fitbit devices, among others, to track their daily steps, distance, energy expenditure, and in some cases even their heart rate. These tools are becoming so widespread that they have become the focus of numerous research studies, which seek to understand how best to design these type of devices and their interactive features. Even with this new line of research, we currently know very little about the theoretical basis of what might work for discretionary users of self-trackers.

The current study was designed to develop an understanding the relationship between BCTs and physical activity behavior change for individuals who freely choose to use physical activity tracking devices. The primary aims of this study were to: a) determine what BCTs are used by a group of long-term discretionary users of physical activity self-trackers and b) determine the relationship between BCT use and change in physical activity over time. As physical activity tracking devices and applications become ubiquitous it is important for individuals working in preventive medicine and public health to understand how people integrate these devices into their everyday lives. The current study was proposed to be starting point for both the research and commercial communities that are seeking to better understand the role of physical activity devices in the lives of individuals who use them.
