Discussion

Physical activity measurement, especially in the field of public and population health research, has typically taken the view of participants as *factors* in the research process. This closely resembles the role individuals possessed in the first stage of HCI research - participants were measured were required to use systems without regard to their personal interest in the outcomes of the research. However, there has been a remarkable shift in the last few years. As mentioned previously, a large number of individuals are not taking an active role in the measurement of their own behavior. This discretionary use of phyiscal activity trackers - individuals are freely choosing to measure their own health behavior - signals a unique opportunity for the future of physical activity research. There exists

Limitations of physical activity tacker data for public health research.
Physical activity trackers are not cheap, typically costing between $60 - $300 per device.

### Self-Directed Technology Use
This move toward personal self-tracking was bolstered not just by the injection of new sensors and technologies into society, but also by shifts in our collecting understanding of the relationship between technology and the individuals who use it. Much of the research in this area has been and continues to be conducted in the field of *Human-Computer Interaction* (HCI). The history of the use of computing systems (of which wearable sensors are just one modern example) closely resembles that of all machines. First, computers were designed for highly specified functional purposes and their human operators were trained with an emphasis on error reduction and increasing performance efficiency. This led to research on improving the design of computing tools and systems - in essense working with the factors that improved the operation of the system [@Grudin2005]. Bannon [-@Bannon1991] described this approach, typically reffered to as *Human Factors* research, as treating the individual as a "a passive, fragmented, de-personalised, un-motivated individual." An underlying theme during this stage of research was the understanding that the use of the technology was nondiscreationary. That is, individuals were requried to use the technology to complete the necessary tasks at hand. However, as personal computing and technology use became a more ingrained part of the human experience individuals began to express choice in not just what they chose to use, but also the nature of how they interacted with software and hardware. The focus of HCI research mirrored this shift and began to examine individuals as *human actors* [@Bannon1991]. This has led to an emphasis on understanding the usability and design of


Why do pedometers increase physical activity? The following are adapted from Tudor-Locke & Lutes [-@Tudor-Locke2009a]:
1.	“Pedometers offer a simple estimate of physical activity volume in terms of steps taken. This uncomplicated and straightforward output it a direct indicator of movement as a result of behavioral choices.” (pg. 983) - Pedometer are easy to understand and the information is a direct reflection of real-world behavior.
2.	The information is personal and meaningful because it is about the user.
3.	Inherent, immediate visual feedback offers “instantaneous awareness to the end-use that can be directly acted upon.” The information is available in real-time and an individual is able to see the effect of choice and actions on the outcome.
4.	The ability to check one’s progress in real-time is useful for setting goals, and checking and evaluating progress.
5.	Recoding, storing, interacting with, and visualizing pedometer data provides additional mechanisms for personalized feedback, and a deeper understanding of behavior patterns.
6.	The ability to transfer data and share it with others introduces social constructs such as accountability, support, comparison, and competition.
