---
title: "Fitbit Research"
author: "Ernesto Ramirez"
date: "March 2, 2016"
output:
  github_document:
    toc: true
    toc_depth: 3
    html_preview: false
  pdf_document:
    toc: yes
  html_document:
    toc: true
    toc_float: true
  word_document:
csl: apa-no-ampersand.csl
bibliography: library.bib
---

# Fitbit Physical Activity Trackers

In September 2008, the first verstion of the Fitbit activity tracker was unveiled at the TechCrunch50 Conference. At the time, it was described as "a small, wireless device, the size of a thumb" that used a tri-axial accelerometer to measure and track steps, distance, energy expenditure, and sleep [@Miller2008]. The first Fitbit devices were distributed on year later in the fall of 2009 to its first customers, and cost $99. The initial device included a "base station" that combined wireless data transfer and battery charging (when the device was connected to the base station). The battery lasted for approximately seven days, and the device would sync with the user's online account whenever it was in range of a base station connected to a internet-conected computer. The device itself included a LED screen and a physical button. By pushing the button a user was able to cycle through the data the device had captured for the current day including: steps, distance traveled, energy expenditure (calories burned), and a flower icon that grows (or shrinks) according to activity levels over the last three hours [@FitbitManual].

[FIGURE TK. FITBIT & BASE STATION]

Since 2009 Fitbit, Inc. has released an additional ten tracking devices of which 8 are currently available for purchase (see Table TK for a description of all devices - TABLE FITBITDEVICES). Each of these devices, whether worn as a clip or on the wrist, are based on a tri-axial accelerometer and proprietary data processing algorithms. As Fitbit has been widely adopted as a method for personal physical activity measurement, their has been considerable interest from the research community for understanding it's utility as both a measurement tool and intervention component.

## Validity
To date, Fitbit has not publically released any information related to the accuracy of their different devices. They indicate, on a webpage addressing accuracy concerns, that they have "performed multiple internal studies to rigorously test the accuracy of Fitbit trackers." and that their testing has "confirmed that our trackers are some of the most accurate wireless tracking devices.", however none of these studies are available to the general public or research community [@FitbitAccuracy].

 The author, in conjunction with collaborators at the Center for Wireless and Population Health Studies and the Department of Computer Science, has examined the validity of the Fitbit Ulta in 2012. In one study of 17 adults we found evidence indicating the Fitbit Ultra performs adequately for structured activities in outdoor and laboratory environments. The magnitude of the difference between the Fitbit and direct observation of step counts (M(SD); range) was small across all activities when worn on the waist (2.0%(4.7%); -6 – 23%) and the bra (0.8%(4.3%); -11 – 15%). A significant effect for speed was found indicating that at higher locomotor speeds (e.g. jogging) the Fitbit underestimates the number of steps taken [@ramirez2012]. Since 2012, a number of studies have examined the validity and reliability of various Fitbit devices. Everson, Goto, and Furberg [-@Evenson2015] recently published a systematic review of the validity and reliability of activity trackers, including Fitbit. They  identified 22 studies published since 2012 that examined the validity and/or reliabilty of the data captured by one or several of the six following Fitbit devices: the Fitbit Classic (original), Fitbit Ulta, Fitbit One, Fitbit Zip, and Fitbit Flex. Twelve studies examined the validity of reported steps for Fitbit devices. Overall, steps reported by Fitbits worn at the waist (Classic, Ultra, One, and Zip) were highly correlated (>= .80) with direct observation and validated measurement tools such as the Yamax CW-700 pedometer and Actigraph GT3X accelerometer. The Fitbit Flex, which is worn at the wrist was found to slighly less accurate. One study examined the validity of the reported distance by the Fitbit One, and it was found to overestimate distance at slow speeds and overestimate at fast speeds. It should be noted that Fitbit recommends calbrating the user's actual stride length to achieve optimal distance measurement for walking and running [@FitbitStride2016]. Fitbit also reports minutes in four activity intensity categories (sedentary, lightly active, farily active, very activty). When compared to established cutpoints for research accelerometers, there does not appear to be a consensus on how accurate these measurements are. One study reported a very high correlation for the Fitbit Zip, while a second study reported low aggreement for both the Zip and One. Lastly, for energy expenditure, across seven studies the Classic, Ultra, Zip, One, and Flex tended to underreport total energy expenditure.

## Reliability
Everson and colleagues located seven studies that examined interdevice reliability of Fitbit devices. That is, studies examining reliabilty only examined multiple similar devices and/or location placement, but did not test wheter a single device remained reliable under consistent conditions. For steps, the Classic, Ultra, One, and Flex showed high reliability for walking and running. Reliability was also very high for different trackers (of the same type) and wearing in different locations (hip vs. pocket or different wrists) for both distance (one study) and energy expenditure (two studies).

Overall the authors conlcuded that for the tested devices there is high validity for steps, and high interdevice reliability for steps and energy expenditure. It should be noted that to-date no validity or reliability studies have been published for the Fitbit Force (recalled), Fitbit Charge, Fitbit Charge HR, or Fitbit Surge.
