---
title: "Introduction"
author: "Ernesto Ramirez"
date: "January 28, 2016"
output:
  github_document:
    toc: true
    toc_depth: 3
    html_preview: false
  pdf_document:
    toc: yes
  html_document:
    toc: true
    toc_float: true
  word_document:
csl: apa-no-ampersand.csl
bibliography: library.bib
---
#Introduction

Any casual observer of technological trends has seen the rise of personal physical activity monitors. Since Fitbit introduced the first advanced wearable activity tracker in 2009, Fitbit has inspired a range of activity tracking devices and applications such as the Jawbone UP, Nike Fuelband, and Garmin Vivofit , and over 60 additional devices, with annual sales of  over $350 million [@Ramirez2014; @BrianDolan]. Smartphone manufactures have also taken notice and have built dedicated measurement and processing systems into their devices. Public health and research institutions as well as funding agencies have begun to see the value in the vast amounts of data that is being collected by individuals tracking their own physical activity. However, there is a lack of understanding of how individuals use these devices during the normal course of their lives, how they understand and develop relationships with the device’s explicit behavioral design characteristics, and the relationship between device use and behavior change.

This study was designed to build on prior work across the fields of health behavior research and human computer interaction using a three-phase mixed-methods approach. Phase one explored the use of self-directed and device-directed behavior change techniques in individuals who use physical activity self-tracking devices through in-depth interviews and qualitative analysis. Phase two explored the the relationship between behavior change technique use and change in physical activity over time. Finally, phase three explored contextual similarities and differences in behavior change technique use across participants.

_Primary Aims_

This study has two primary aims:

1.		Determine what behavior change techniques (BCT)s are used by a group of long-term discretionary users of physical activity self-trackers.

2.		Determine the relationship between BCT use and:
  +	Change in daily total steps over time.
  +	Change in daily time spent in moderate-to-vigorous physical activity (MVPA) over time.

_Hypotheses_

1.		Individuals who use physical activity trackers use a variety of BCTs that are embedded in the design of their devices.

2.		The number of BCTs used by individuals will be a significant predictor of physical activity change over time as measured by daily steps and daily MVPA.
+ The number of BCTs under the domains of “Goals and Planning” and “Feedback and Monitoring” used by individuals will be positively associated change in physical activity (daily steps and daily minutes of MVPA) over time.
+ The use of BCTs that are not explicitly included in the design of the Fitbit system will be positively associated with change in physical activity (daily steps and daily minutes of MVPA) over time.
