---
title: "Methods"
author: "Ernesto Ramirez"
date: "January 27, 2016"
output:
  word_document:
csl: apa.csl
bibliography: library.bib
---
# Methods
## Research Design.

This study was designed to elicit both qualitative and quantitative information from individuals who had been using a physical activity tracking device (Fitbit) for long period of time (>= 90 days). Participants recruited to participate in this research study were asked to complete two phases in order to participate in the study. In the initial phase participants who met the inclusion criteria and consented to be included in the study were asked to connect their Fitbit accounts to the Fitabase analytics system (Small Steps Labs, San Diego, CA, USA). This allowed participants to grant access to their historical data, collected through their Fitbit device, to the investigator. Once participants completed phase one they were asked to take part in a two-stage interview in-person, via phone, or via a web-video conference. Each interview was designed to last between 1.5 and 2 hours. The first stage of the interview consisted of gathering demographic data and completing various psychosocial measures. This lasted approximately 30 minutes. The second stage of the interview was a semi-structured interview and conversation with the participant that covered a variety of topics related to the participants’ use of the Fitbit, the participants’ relationship with the data it collects, and the use of behavior change techniques. The institutional review board from the University of California, San Diego approved this study.

### Setting
As participants were able to complete both phases of the study remotely, this study was open to individuals living in the United States and abroad.

### Recruitment
Participants were recruited through a variety of web and personal channels. Recruitment materials (see Appendix TK) that described the study were posted to the following locations:

+  Fitbit subreddit (available at <http://reddit.com/r/fitbit>)
+  Fitbit discussion forums (available at <https://community.fitbit.com/t5/Discussions/ct-p/discussions>)
+   Quantifiedself.com forums (available at <https://forum.quantifiedself.com>)
+   Quantified Self Facebook group (available at <https://www.facebook.com/groups/quantifiedself/>)

These online groups and websites are open to anyone and are used to announce events and opportunities, engage in open discussion, and coordinate group activities. The primary investigator posted under his own account or under an account labeled, "UCSDFitbitStudy". Snowball sampling was also used to recruit additional participants. At the conclusion of the interview participants were asked to recommend study participation to individuals who are listed in their “Fitbit Friends” network and additional friends or family who meet the inclusion criteria. Additional copies of of the recruitment materials were provided to participants who expressed interest in sharing the study with others. All recruitment materials prompted individuals to contact the primary investigator via email if they were interested in participating. The primary investigator replied to all individuals who expressed interest with additional information about the study and a prompt to schedule a brief (10 to 15 minute) screening phone call. If the individual met the inclusion and exclusion criteria (described below) they were provided a copy of the informed consent and the study methods were described in detail. If the individual consented to be a participant in the study they were prompted to schedule an interview with the primary investigator and were given detailed instructions on how to connect their Fitbit account to the Fitabase analytics system.

### Inclusion and Exclusion Criteria

Inclusion and exclusion criteria consisted of: 1) men and women between 18 and 60 years old, 2) current user of a Fitbit activity tracking device, 3) a minimum of 90 days of use of any combination of Fibit activity tracking devices, 4) the ability to use video teleconferencing systems (e.g. Skype, Google Hangout, Facetime), 5) willing and able authorize the primary investigator to access and download a copy of Fitbit data via the Fitabase analytics system, 6) no more than six (20% of total sample size) participants who identify as early adopters of self-tracking practices as derived from their membership in Quantified Self meetup groups or online communities. Participants were not excluded based on ethnic background, location, or health status.

## Primary and Secondary Outcome Measures
### Fitbit Data Collection
In addition to the user-centered components of the Fitbit system (device, application, and dashboard), Fitbit has developed and provides access to an application programming interface (API) so that outside entities can build tools and services to enhance the user experience. The API allows a third party to access and add to the data currently gathered and stored in the Fitbit database. These read/write privileges allow an application developer to build visualizations, reminder tools, and add additional services to existing behavioral or data storage platforms.

In order to access Fitbit data from research participants, the Fitabase service was used. Fitabase provides a simple platform for authenticating participants and accessing the data gathered while using a Fitbit device. Fitabase has been chosen because all data is stored in a secure server, and its history of collaboration with research institutions [@Cadmus-Bertram2015; Choi2015; @Diaz2015a; @Hartman2015; @Schaefer2016]. Participants were be asked to authorize the Fitabase system to access their Fitbit data and make it available for download for analysis. All participants authorized the Fitabase system via an online portal.

Online Authorization. The participant was asked for a valid email address to send the authorization link. The author then created a profile for the participant that included their assigned unique study identifier. A link to Fitabase Authorization Page was then emailed to the participant. The online Fitabase Authorization Page contains the same text as the Fitabase Authorization page (Appendix TK). At the bottom of the online Fitabase Authorization page a “connect your device” button was presented. The participant was asked to read the authorization page and if they agreed, to connect their Fitbit and authorize Fitabase to read and access their Fitbit data. It important to note that the personal login information for each participant was be entered outside of the view of the author and is not passed to the Fitabase system (it uses the OAuth protocol established for API authentication). When the participant entered their information and connected their Fitbit account to Fitabase the online authorization was completed. This completion also signaled an acceptance of the Fitabase Terms of Use and Privacy Policy [@Fitabase2016].

### Fitbit Data
For each participant, data at the interday (daily aggregate values) level, and at the intraday (minute-by-minute values) level was available for downloading and analysis. At the interday level the following data was downloaded: Steps, Distance Traveled, Very Active Minutes, Fairly Active Minutes, Lightly Active Minutes, Sedentary Minutes, and Estimated Energy Expenditure. At the intraday level, the following data was available and was downloaded: Steps, Intensity Classification, MET Values, and Estimated Energy Expenditure. All Fitabase data files were downloaded in CSV format. The current study did not examine sleep, weight, or dietary data. If that data was available for a participant via the Fitabase interface it was not viewed, downloaded, or saved as part of the research protocol. All participant data files were checked for completeness. In rare cases a participant's daily and/or intraday data files were missing data. In these cases the primary investigator requested that Fitabase re-run the data request from Fitbit in order to generate complete data files.

### Interview
A short set of interview questions was be prepared prior to recruitment and was refined to reflect emerging knowledge as the research process progressed. The interviews were conducted in order to uncover the narratives and processes that reflect the realty of using a physical activity tracker. An Informed Grounded Theory approach was used to develop the initial questionnaire [@Thornberg2012]. This approach included using knowledge about the design of the Fitbit system, available features and functionality, and behavior change techniques that were identified in prior research conducted by Lyons et al. [-@Lyons2014].  The interview guide was designed with a three-level hierarchical structure: 1) sections of questions based on a general theme, 2) main questions designed to elicit answers related to the section theme, and 3) probing questions that prompted more specific answers or feedback relating to the main question(s). The final interview guide is available in Appendix TK.

Interviews were audio-recorded by the investigator and then transcribed using a third-party transcription service (CastingWords, LLC; www.castingwords.com). One interview was plagued by audio issues and was transcribed by the investigator. All transcripts were checked for accuracy upon receipt.

#### Demographic Information.
Participants completed a demographic questionnaire that included birth year, gender, race/ethnicity, education, height, weight, marital status, and household income.

## Data Processing
### BCT Identification
As stated previously, previous research has identified BCTs that were implemented by Fitbit in one device (Fitbit Force) and the associated mobile and web applications [@Lyons2014]. As the device used in that analysis was recalled and there have been numerous updates to available devices and the mobile and web applications, a review of the BCTs available in the Fitbit system was conducted. In addition to a review of the mobile application and website features, the investigator used personal experience with using multiple devices (Fitbit, Fitbit Ultra, Fitbit One, Fitbit Charge HR) to track his physical activity since 2011. Additionally, a review of the features of all available Fitbit devices as described on the Fitbit website (www.fitbit.com/compare) was conducted.

### Fitbit Data Processing
There was a wide range for the length of time participants had been using a Fitbit device. To simplify understanding the the term, "Fitbit user period" is used to describe the total length of time a participant has been in identified as a user with the Fitbit ecosystem, from the date of the creation of a Fitbit use account until the date of their interview. It is possible that the Fitbit user period does not accurately reflect the total time a participant was using a Fitbit device. As this data is retrospective in nature there is not guarantee that the participants were using their device and collecting physical activity information for each of the days present in their data files. Participants may have lost a device for a period of time, forgotten to wear their device, or even chosen not to wear it for a particular day or period of time. Even if the device is not worn, and it does not move, the data is still synced to Fitbit and made available through the API. Typically this results in a day with values equal to zero for physical activity data (steps, active minutes, distance, etc.). These days are included when the historical data is accessed. This complete historical file was used in order to calculate the Fitbit user period. Participants in this study ranged from relatively new to using a Fitbit device to long-term users, with a range of 98 to 2,014 days. On average, participants in the current study had mean user period of 688 days (SD = 487.54). The initial review of all historical Fitbit data from the 30 participants in this study resulted in a total of 20,637 participant-days of available Fitbit data. To better classify the available data, and use data that most accurately reflected actual device wear a multi-step wear time classification process was conducted.

#### Wear Time Processing
The first step for determining valid wear days was to detect and remove all days with zero steps. This initial pass reduced the full data set from 20,637 to 17,232 person-days.

The second step involved a  weartime validation process commonly used when processing physical activity accelerometer data. Initially, minute-level step values were used to approximate the commonly used count measure produced by research accelerometers such as the ActiGraph GT3X. However, since accelerometer counts are derived from the intensity of the accelerometer movement in Actigraph models [@ActigraphCount], additional data sources provided by Fitbit were explored. Fitbit states:

>All Fitbit trackers calculate active minutes using metabolic equivalents (METs). METs help measure the energy >expenditure of various activities. Because they do so in a comparable way among persons of different weights, METs are >widely used as indicators for exercise intensity. For example, a MET of 1 indicates a body at rest. Fitbit trackers >estimate your MET value in any given minute by calculating the intensity of your activity. [@FitbitMET]

Since the minute-level MET value provided by Fitbit is a more appropriate measure for inferring the movement of the actual device, and not a behavioral measure, like steps, this was used for wear time analysis.

Minute-Level data files containing the date/time stamps and MET values were downloaded from Fitabase for each participant. The data was processed in R and the "accelerometry" package was used to analyze and flag period of non-wear time [@rstats; @accelerometry]. The data was processed using parameters commonly used for processing accelerometer data in physical activity research [@Troiano2008; @Choi2011]. These parameters include a minimum non-wear window of 90 minutes, a tolerance of two minutes for non-zero counts within a non-wear window, a maximal tolerance of two METs for a minute within the non-wear window. Additionally, processing was set to use a moving window to go through every possible 90-minute window in the data. Days were classified as valid if at least 600 minutes was classified as valid wear time within a 24hr day period using this processing method. Processing the minute-level MET data for each participant for algorithmically determined non-wear time resulted in further reduction to 15,954 valid person-days.

#### Visual Analysis
To further inspect the Fitbit data for characteristics that would indicate invalid days a visual analysis of the data was employed. Each participant's minute-level step and MET data were plotted and inspected for uncharacteristic values and patterns. Specifically, this visual analysis of the minute-level data allowed for the identification of periods of data that could be attributed to device malfunctions or non-locomotor activity. Figure [TK] provides an annotated example of data that was identified as inconsistent with normal activity patterns.

#### Censuring Abnormal Data
After the visual analysis it was determined that step values greater than or equal to 200 steps per minute should be classified as abnormal. As 200 steps per minute could be possibly achieved by the participants a conservative process was used to eliminate valid days that included abnormal minutes. Days previously marked as valid were censured if greater than ten percent of their daily step total was attributed to abnormal minutes.

After the processing steps described above a total of 15,941 valid participant-days of data were observed  in the dataset. The ratio of valid days to total available days per participant ranged from 10.22% to 99.27%. The number of days of data at each step in the previously described analysis is presented in Table [TK]. A visual representation of all valid wear days is presented in figure [TK]. It was determined that individuals who possessed less that 50% valid days to total available days (Valid Days / Fitbit User Period) would not be included in the statistical analysis as their data represents inconsistent wear behavior and may not be representative of actual physical activity behavior. These individuals' interviews were retained and included in the contextual analysis.

```{r, results = 'asis'}
library(knitr)
library(plyr)
load("~/Dropbox/Dissertation.Data/FitbitData/ProcessedData/Daily.Activity.Final.rdata")
WearTable <- ddply(Daily.Activity.Final, c("id"), summarise, 'Initial Available Days'=length(id),
                   'Valid Days (MET Processing)'=sum(ValidDay.Counts),
                   'Valid Days (Censured)'=sum(ValidDay.Censured),
                   'Valid Days (Final)'=sum(Valid.Final)
                   )
kable(WearTable, caption = "Table [TK]")
```

#### Outcome One - Steps per Day
As

### Hypotheses & Sample Size
The first aim of this study was to determine what BCTs are used by a group of long-term discretionary users of physical activity self-trackers. This aim was addressed by using a systematic coding approach that was applied to the interviews conducted with each participant. It was hypothesized that participants used a variety of BCTs during their discretionary use of a Fitbit physical activity tracking device. The second aim of this study was to develop an understanding of the relationship between BCTs and physical activity behavior change for individuals who freely choose to use physical activity tracking devices. A review of behavioral interventions for physical activity and other health behaviors indicates that there is a positive relationship between a) the use of specific BCT domains, and b) the total number of BCTs used and physical activity outcomes. However, additional variables may impact physical activity behavior and/or moderate the influence of BCT use on change in physical activity over time. The null hypothesis is that the use of behavior change techniques will not be significantly related to physical activity behavior change over time. The alternate hypothesis is that behavior change techniques used by individuals will be a significant predictor of physical activity change over time as measured by daily steps and daily MVPA derived from a Fitbit. Furthermore, the use of BCTs that are identified as being not natively available in the design of the Fitbit system (device, app, and website) will be positively associated with change in physical activity (daily steps and daily MVPA) over time. As this study was designed to be exploratory a small sample size of 30 participants were recruited.

### Coding Interviews
As mentioned previously, an Informed Grounded Theory approach was used to guide this qualitative portion of this study. This approach is based on the use of prior research and literature to inform and focus attention on specific ideas or concepts during the qualitative research process [@Thornberg2012]. By using prior research in the area of behavior change as well as findings from similarly designed studies (i.e. Fritz and colleagues [-@Fritz2014]), this process allowed the study to build on the existing knowledge in this area.

Coding was conducted using a multi-step, iterative process that allowed the investigator to continually refine and revise the application of codes assigned to all the available interviews. First, all interview transcripts were read in order for the investigator to familiarize himself with the content and nature of the transcript content. Next, each participant's answers to the interview questions were coded according to the 16 BCT domains present in the BCTTv1 [@Michie2015]. After each participant's interview was coded at the "domain level" the interviews were re-coded at the "technique level." Each answer, quotation, or section that was previously coded as pertaining to one or more BCT domains was reviewed and assigned one or more of the 93 specific BCTs. The identification of BCTs was based on the definitions included with the published BCTTv1, however it should be noted that the locus of control was shifted so that the BCTs identified as being implemented by the participant and not by an intervention.

All coding was conducted using Atlas.ti for Macintosh systems, version 1.0.44 (ATLAS.ti Scientific Software Development, GmbH).

### Statistical Modeling
A multi-level model was decided to be an appropriate approach to address the second aim. Multi-level modeling allows for the number of observations per participant and the spacing of the observations to vary as individual (per participant) growth trajectories can be modeled. In the case of this study, it can be said that it is a two-level design, with repeated observations (days) nested within each participant. Additionally, multi-level modeling allows for missing data to be present in the analyzed data set as there is an assumption that data is missing at random. This assumption, coupled with the additional assumption that an individual's data is a true random sample of data from their true growth trajectory, allows for interpretation of model estimates when measurements are missing [@Singer2003a]. However, it should be noted that the multilevel uses full-information maximum likelihood to estimate the model parameters and those parameters are reflective of what would have been observed if the data were complete [@Hoffman2007]. In the data gathered for this study, five participants had observed data that was systematically missing for extended periods of time and that their available data represented less than 50% of their Fitbit use period. It was decided that these participants should not be be included in the modeling process described below as it was not reasonable to assume their data was missing at random.

Mutli-level modeling allows for estimation of both fixed and random effects. Fixed effects are estimates that remain constant across groups, in the case of this study, across all participants. Random effects are the effects of variables that are allowed to vary across individuals [@Hoffman2007]. Both fixed and random effects were explored in the analysis, specifically, demographics variables and BCT use were retained in the models as fixed effects. Random intercepts and random slopes (the effect of time) were fitted to the model allowing the intercept and slope to vary by individual.

#### Models & Variables
The statistical analysis include a multi-step approach to produce final model estimates. First, a *demographic model* was produced. This model included only the demographic variables (including a "data affinity variable") as predictors in a model. Backwards stepwise deletion was performed. All non-significant effects, starting from the random effects, and then fixed ones, were excluded from the final demographic model, and model fit was evaluated. Next, the use of BCT within the 16 domains were entered into the model in a two-step procedure. All BCT domains were evaluated as dichotomous variables; if a participant used any techniques within a BCT domain then the domain level variable was coded as being used by the participant. The initial BCT model included all BCT domains that that were identified as containing BCTs that were available to the participant in the design of the Fitbit system. Again, backwards stepwise deletion was performed and model fit of the initial BCT model was evaluated. Lastly, the remaining the dichotomous variables reflecting the use of BCT domains that were not identified as available in the Fitbit system were included in addition to any variables retained in from the initial BCT model.

In order to address the hypothesis that a dose-response relationship exists between BCT use and the activity outcome variables (described below), another set of models was evaluated. This process mirrored the model building described for the BCT domain models. However, the BCT domain variables were re-structured to reflect the relative percentage of techniques used within the domain. The number of techniques used per domain was identified for each participant and divided by the total number of available techniques for that domain. For example, a participant may use 5 of the 9 (55.56%) *Goals and Planning* techniques, but another participant may use only 2 (22.22%). The BCTTv1 indicates that each domain has between three and eleven techniques [@Michie2015]. The percentage of techniques used within each domain was chosen, rather than absolute number of techniques, in order to standardize each domain. Using the presence of each unique technique was considered, but using 93 separate predictors could easily lead to over-fitting. Additionally, techniques within a domain could be assumed to inherently correlated, thus allowing for this variable reduction technique. Again, BCT domains that were identified as being included in the design of the Fitbit were entered and evaluated first (initial BCT model), and then all other BCTs were entered and evaluated.

This modeling process led to the creation of five models for each of the two main outcomes of interest. These outcomes represented the repeated measures nested within participants over time, and each outcome was assessed independently. The first outcome of interest was steps per day. The steps per day variable was either the step total for each day that was evaluated as being a valid day of Fitbit wear, or was considered missing.


### Contextual Analysis
It was hypothesized that the use of BCTs that fall under the domains of “Goals and Planning” and “Feedback and Monitoring” (see Table TK) will be significantly related to the above-mentioned outcomes, but that the way that individuals employ those BCTs are not always congruent. Additional analysis of the qualitative data gathered through interviews was be conducted in order to tease out the contextual information surrounding the BCTs that were identified during the coding process. This contextual analysis was conducted in order to provide a richer understanding of how individuals explore and employ BCTs during discretionary use of self-tracking tools. This analysis was undertaken because the investigator began to observe marked differences in how participants employed and processed the same behavioral techniques. It is believed that this method may provide a path forward for a more systematic approach to exploring BCT importance in future studies.
