---
title: "Analytical Methods"
author: "Ernesto Ramirez"
date: "February 25, 2016"
output: word_document
---

The current analytical methods as described in my most recent aims document described a process for categorizing the dependent variable to describe change in physical activity (steps and MVPA) over time. Initially, I thought it would be possible to replicate the methods of a previous study that have described change over time for pedometer data. This study used simple linear regression for steps per day and weekly variability (95% CI). However, the data-sampling period was consistent across all participants (1yr) and thus trends are easily comparable between participants. My data includes 30 participants who have different sampling periods (97-1977 days) as well as differing patterns of missing data. This type of longitudinal data necessitates a different modeling strategy. Through discussion with Greg Norman applying a multi-level model was decided as an appropriate approach. Multi-level modeling allows for the number of observations per participant and the spacing of the observations to vary as individual (per participant) growth trajectories can be modeled. Furthermore, in order to model change over time, I am proposing to use the week-to-week change as determined by the intercept and slope of a linear regression over a rolling 14-day window. I have decided to use the week-to-week change over time for three reasons: 1) current physical activity guidelines are based on weekly minutes of activity, 2) current society has a natural inclination to cognitively process chunks of time in weekly increments, and 3) Fitbit delivers a weekly communication about each week's physical activity and indicates change compared to the previous week.



