---
title: "Results.Demographics"
author: "Ernesto Ramirez"
date: "January 27, 2016"
output:
  github_document:
    toc: true
    toc_depth: 3
    html_preview: false
  pdf_document:
    toc: yes
  html_document:
    toc: true
    toc_float: true
  word_document:
csl: apa-no-ampersand.csl
bibliography: library.bib
---

Results

Participants. Participants were recruited between June and August 2015. Thirty-seven individuals responded to recruitment postings and expressed an interest in participating in the study. Of the 37 individuals who expressed interest, 33 were screened for inclusion in the study. All 33 met the inclusion criteria and were asked to schedule the interview and connect their Fitbit data to Fitabase. Thirty-two individuals scheduled interviews and connected their Fitbit data to Fitabase, however two participants were not able to complete the interview due to time constraints. The Fitabase data connection was deleted for the two participants who were not able to complete the interview.  In total, 30 participants fully participated in the current study.

Table TK displays the demographic information for the sample that completed the study. The sample consisted of 11 (37%) men and 19 women (63%). Participants were between 23 and 60 years old, with a mean age of 36.60 years (SD = 10.56). The majority of participants reported that they were of Caucasian race/ethnicity (73%), were college educated (80% completed college or graduate degree), and worked full time (83%).  Half the sample reported being married with another 40% reporting as “Single and Never Married.” Additionally, 33% of the sample reported a household income in excess of $100,000. Median income was $80,000 - $89,000 (one participant abstained from reporting household income information). Height and weight was self-reported and BMI was calculated.  Participants had a BMI range of 17.28 to 59.67 kg/m2, with a mean of 25.85 kg/m2 (SD = 8.47). Two participants were classified as “underweight” (6.67%), 24 participants (80%) were classified as “normal weight”, two participants were classified as Obese Level I, and two participants were classified as “Obese Level III (Extreme Obesity)”.

Fitbit
Device & Use
As previously mentioned, at the time of this study there were six different Fitbit devices available for purchase. Each of the six available devices were represented in the data set, with an additional device that is no longer available for purchase also represented (Fitbit Ultra).

Usage  & Wear Time
There was a wide range for the length of time participant had been using the Fitbit.

Steps

Distance

Activity Classification

Energy Expenditure
