---
title: "Weartime"
author: "Ernesto Ramirez"
date: "January 27, 2016"
output:
  github_document:
    toc: true
    toc_depth: 3
    html_preview: false
  pdf_document:
    toc: yes
  html_document:
    toc: true
    toc_float: true
  word_document:
csl: apa-no-ampersand.csl
bibliography: library.bib
---
#Fitbit Data Processing

All historical data for each participant was collected using Fitbase. Briefly, all data from a participant's account was made available through the Fitbit API and the Fitbase system. Data was collected and downloaded to include every day from the time the participant first signed up with Fitbit (Initiation Date), until the day of the participant's interview (Interview Date).

As this data is retrospective in nature there is not guarantee that the participants were using their device and collecting physical activity information for each of the days present in their data files. Participants may have lost a device for a period of time, forgotten to wear their device, or even chosen not to wear it for a particular day or period of time. Even if the device is not worn, and it does not move, the data is still synced to Fitbit and made available through the API. Typically this results in a day with values equal to zero for physical activity data (steps, active minutes, distance, etc.). To better classify the available data, and use data that most accurately reflected actual device wear a multi-step wear time classification process was conducted.

##Wear Time Processing: Flagging
Initially, minute-level step values were used to approximate the commonly used count measure produced by research accelerometers such as the ActiGraph GT3X. However, since accelerometer counts are derived from the intensity of the accelerometer movement in Actigraph models [@ActigraphCount], additional data sources provided by Fitbit were explored. Fitbit states:

>All Fitbit trackers calculate active minutes using metabolic equivalents (METs). METs help measure the energy >expenditure of various activities. Because they do so in a comparable way among persons of different weights, METs are >widely used as indicators for exercise intensity. For example, a MET of 1 indicates a body at rest. Fitbit trackers >estimate your MET value in any given minute by calculating the intensity of your activity. [@FitbitMET]

Since the minute-level MET value provided by Fitbit is a more appropriate measure for inferring the movement of the actual device, and not a behavioral measure, like steps, this was used for wear time analysis.

Minute-Level data files containing the date/time stamps and MET values were downloaded from Fitabase for each participant. The data was processed in R and the "accelerometry" package was used to analyze and flag period of non-wear time[@rstats; @accelerometry]. The data was processed using parameters commonly used for processing accelerometer data in physical activity research [@Troiano2008; @Choi2011]. These parameters include a minimum window of 90 minutes, a tolerance of two minutes for non-zero counts within a non-wear window, a maximal tolerance of two METs for a minute within the non-wear window. Additionally processing was set to use a moving window to go through every possible 90-minute window in the data. Days were classified as valid if at least 600 minutes of wear time was classified within the day using this processing method.

##Visual Analysis
To further inspect the Fitbit data for characteristics that would indicate invalid days a visual analysis of the data was employed. Each participant's minute-level step and MET data were plotted and inspected for uncharacteristic values and patterns. Specifically, this quick visual analysis of the minute-level data allowed for the identification of period of data that could be attributed to device malfunctions or non-locomotor activity. Figure [TK] provides annotated example of data that was identified as inconsistent with normal activity patterns.

##Censuring Abnormal Data
After the visual analysis it was determined that step values greater than or equal to 200 steps per minute should be classified as abnormal. As 200 steps per minute could be possibly achieved by the participants a conservative process was used to eliminate valid days that included abnormal minutes. Days previously marked as valid were censured if greater than ten percent of their daily step total was attributed to abnormal minutes.




```{r, results = 'asis'}
library(knitr)
library(plyr)
load("~/Dropbox/Dissertation.Data/FitbitData/ProcessedData/Daily.Activity.Final.rdata")
WearTable <- ddply(Daily.Activity.Final, c("id"), summarise, 'Initial Available Days'=length(id),
                   'Valid Days (MET Processing)'=sum(ValidDay.Counts),
                   'Valid Days (Censured)'=sum(ValidDay.Censured),
                   'Valid Days (Final)'=sum(Valid.Final)
                   )
kable(WearTable, caption = "Table [TK]")
```
